version: '3.4'

services:
  vscodetypescriptdebugging:
    image: vscodetypescriptdebugging
    build:
      context: NodeJS Backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
