# Generated by Django 4.0.2 on 2022-02-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinGeckoCoinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('market_cap_rank', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('fully_diluted_valuation', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('total_volume', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('price_change_percentage_24h', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('market_cap_change_24h', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('market_cap_change_percentage_24h', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('total_supply', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('max_supply', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('ath', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('ath_change_percentage', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('ath_date', models.DateTimeField(blank=True, null=True)),
                ('atl', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('atl_change_percentage', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('atl_date', models.DateTimeField(blank=True, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
            ],
            options={
                'db_table': 'coin_gecko_coin_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoinHistory',
            fields=[
                ('symbol', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('total_volume', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True)),
            ],
            options={
                'db_table': 'coin_history',
                'managed': True,
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
