# Generated by Django 4.0.2 on 2022-02-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_coingeckocoininfo_coin_id_and_more'),
    ]
