# Generated by Django 4.0.2 on 2022-02-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_coingeckocoininfo_id'),
    ]

    operations = [
        
    ]
