# Generated by Django 4.0.2 on 2022-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_coingeckocoininfo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coingeckocoininfo',
            name='coin_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
