# Generated by Django 4.0.2 on 2022-02-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_coingeckocoininfo_coin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='ath',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='ath_change_percentage',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='atl',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='atl_change_percentage',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='fully_diluted_valuation',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='high_24h',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='low_24h',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='market_cap_change_24h',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='market_cap_change_percentage_24h',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='market_cap_rank',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='max_supply',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='price_change_24h',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='price_change_percentage_24h',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='total_supply',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coingeckocoininfo',
            name='total_volume',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coinhistory',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coinhistory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coinhistory',
            name='total_volume',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
    ]
