// return string is print data generated by the test.
import {OrderDirection, QueryHelper} from "../../../../GraphQL/QueryHelper";
import {TokenDayData} from "../TokenDayData";
import {print_json_tree} from "../../../../Utils/print_json_tree";
import {getTokenDayData} from "./TokenDayDatas";

async function testGetTokenDayDatas(how_many_print:number):Promise<string>
{
    const qh = new QueryHelper();
    const tokenDayDatas: TokenDayData[] =
        await getTokenDayData(100, 'volumeUSD', OrderDirection.desc);
    // prepare some selections for pretty printing:
    let list_print_str: String = ``;
    for(let i:number = 0; i < how_many_print; i++ ){
        list_print_str +=
            `Token: ${tokenDayDatas[i].token?.symbol}
            id: ${tokenDayDatas[i].token?.id }
            priceUSD: ${tokenDayDatas[i].priceUSD}
            volumeUSD: ${tokenDayDatas[i].volumeUSD}
            number of pools: ${tokenDayDatas[i].token?.poolCount }
         `
    }

    const message:string =
        ` tokenDayDatas:
    `+ `total items: ${tokenDayDatas.length}
    `+ `${list_print_str.toString()} 
    `;
    console.log(message);
    console.log(print_json_tree(tokenDayDatas[0]," "))
    return message;
}

